stages:
  - install
  - build
  - publish

variables: {}

include:
  - project: devops/gitlab-pipes
    file: /templates/node-build.gitlab-ci.yml
    ref: main

include:
  - project: devops/gitlab-pipes
    file: /templates/semantic-release.gitlab-ci.yml
    ref: main
