stages:
  - install
  - build
  - generate
  - publish

variables:
  NODE_VERSION: 20-alpine

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/v2/node-run.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
    ref: main

build:
  artifacts:
    paths:
      - dist/**
      - oclif.manifest.json

generate:
  extends: .node-run
  stage: generate
  variables:
    NODE_COMMAND_SCRIPT: start
  artifacts:
    paths:
      - default.json
