stages:
  - install
  - build
  - publish

variables:
  NODE_VERSION: 18-alpine
  NODE_PACKAGE_MANAGER: pnpm
  NODE_LINT_COMMAND: lint

include:
  - project: devops/pipes
    file: /templates/node.gitlab-ci.yml
    ref: main

  - project: devops/pipes
    file: /templates/semantic-release.gitlab-ci.yml
    ref: main

build:
  artifacts:
    paths:
      - package.json
