name: lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14.x'

      - name: install
        run: yarn

      - name: check formatting
        run: yarn lint:check
